### ISSUE TITLE
Cannot read properties of undefined (reading 'directiveTransforms') 

### ISSUE THREAD

**Issue by P4sca1** [storyblok/storyblok-nuxt-beta#14]
```
 FATAL  Cannot read properties of undefined (reading 'directiveTransforms')                                                                                           

  at node_modules/@storyblok/nuxt-beta/dist/module.mjs:44:31
  at node_modules/hable/dist/hable.js:1:990
  at node_modules/hable/dist/hable.js:1:208
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async Nuxt.callHook (node_modules/hable/dist/hable.js:1:959)
  at async Builder.build (node_modules/@nuxt/builder-edge/dist/builder.js:248:5)
  at async Object._buildDev (node_modules/@nuxt/cli-edge/dist/cli-dev.js:85:5)
  at async Object.startDev (node_modules/@nuxt/cli-edge/dist/cli-dev.js:61:7)
  at async Object.run (node_modules/@nuxt/cli-edge/dist/cli-dev.js:50:5)
  at async NuxtCommand.run (node_modules/@nuxt/cli-edge/dist/cli-index.js:370:7)
```

**Comment by P4sca1** [comment]
This issue seems to b e fixes as of version 2.2.0
